
# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    ports:
      - 3306:3306
    container_name: mysql-db
    env_file:
      - ./packages/server/.env
        
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data:
    driver: local
